CREATE TABLE `bucket_dependencies` (
    `bucket_id` VARCHAR(11) NOT NULL,
    `depends_on_bucket_id` VARCHAR(11) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
