# fly.toml app configuration file generated for dumplink-kitchen on 2023-12-04T15:40:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dumplink-kitchen"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]
  [build.args]
    BP_KEEP_FILES = "static/*:resources/*"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/workspace/static"
  url_prefix = "/static"
